name: On Push to Feature Branch

on:
    push:
        branches:
            - '**'
            - '!main'

jobs:
    feature-branch-push:
        name: Feature Push
        runs-on: ubuntu-24.04
        steps:
            - name: Show context
              run: |
                echo "github_ref=${{github.ref}}"