name: On Push to Main Branch

on:
    push:
        branches:
            - main

jobs:
    main-branch-push:
        name: Main Push
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Get the semantic version values for the repo
              id: semantic
              uses: paulhatch/semantic-version@v5.4.0

            - name: Show outputs
              run: |
                echo "github_ref=${{steps.semantic.outputs.version_tag}}"

            - name: Tag the repository with the semantic version
              uses: actions/github-script@v7
              with:
                script: |
                  github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: 'refs/tags/${{steps.semantic.outputs.version_tag}}',
                    sha: context.sha
                  })