name: On Push to Main Branch

on:
    push:
        branches:
            - '!main'
            - '**'

jobs:
    main-branch-push:
        name: Main Push
        runs-on: ubuntu-24.04
        steps:
            - name: Show context
              run: |
                echo "github_ref=${{github.ref}}"